language: go
go:
- '1.10'
services:
- docker
cache:
  directories:
    - "$HOME/google-cloud-sdk"
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
jobs:
  include:
    - stage: build image and push to GCR
      before_install:
        - openssl aes-256-cbc -K $encrypted_8aba50e08a7d_key -iv $encrypted_8aba50e08a7d_iv
          -in gitops.json.enc -out gitops.json -d
        - if [[ ! -d ${HOME}/google-cloud-sdk ]]; then
              curl https://sdk.cloud.google.com | bash;
          fi
        - gcloud auth activate-service-account --key-file gitops.json
        - gcloud config set project gitops-233223
      script:
        - gcloud auth configure-docker
        - docker build -t asia.gcr.io/gitops-233223/gitops-hello-world:${TRAVIS_COMMIT} .
        - docker images
        - docker push asia.gcr.io/gitops-233223/gitops-hello-world:${TRAVIS_COMMIT}
    - stage: trigger k8s config update
      script: echo "done!"


