language: go
go:
- '1.10'
services:
- docker
after_success:
- docker build -t gcr.io/GitOps/gitops-hello-world:${TRAVIS_COMMIT} .
- docker images
before_install:
- openssl aes-256-cbc -K $encrypted_8aba50e08a7d_key -iv $encrypted_8aba50e08a7d_iv
  -in gitops.json.enc -out gitops.json -d
